package by.epam.signsControl.bean;

import java.io.Serializable;

/**
 * bean for jdbc
 *
 * @author Bulgak Alexander
 * @see FactoryType
 * @see Serializable
 */
public class Direction implements FactoryType, Serializable {

    /**
     * generated by Intellij IDEA
     */
    private static final long serialVersionUID = -5364144967319472433L;

    /**
     * Direction id from jdbc
     */
    private int id;

    /**
     * Direction value from jdbc
     */
    private char direction;

    /**
     * empty constructor
     */
    public Direction() {
    }

    /**
     * constructor with all parameters
     *
     * @param id        {@link Direction#id}
     * @param direction {@link Direction#direction}
     */
    public Direction(int id, char direction) {
        this.id = id;
        this.direction = direction;
    }

    /**
     * @return {@link Direction#id}
     */
    public int getId() {
        return id;
    }

    /**
     * @param id {@link Direction#id}
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return {@link Direction#direction}
     */
    public char getDirection() {
        return direction;
    }

    /**
     * @param direction {@link Direction#direction}
     */
    public void setDirection(char direction) {
        this.direction = direction;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Direction direction1 = (Direction) o;

        if (id != direction1.id) return false;
        return direction == direction1.direction;
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (int) direction;
        return result;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Direction{");
        sb.append("id=").append(id);
        sb.append(", direction=").append(direction);
        sb.append('}');
        return sb.toString();
    }
}
