package by.epam.signsControl.bean;

import java.io.Serializable;

public class StandardSize implements Serializable, FactoryType, Cloneable {

    /**
     * generated by IDEA
     */
    private static final long serialVersionUID = -6583064798614414700L;

    /**
     * size
     */
    private int size;

    /**
     * info
     */
    private String info;

    /**
     * @return this object clone
     */
    @Override
    protected Object clone() {
        try {
            return super.clone();

        } catch (CloneNotSupportedException e) {
            // this shouldn't happen, since we are Cloneable
            throw new InternalError(e);
        }
    }

    /**
     * empty constructor
     */
    public StandardSize() {
    }

    /**
     * constructor with all parameters
     *
     * @param size {@link StandardSize#size}
     * @param info {@link StandardSize#info}
     */
    public StandardSize(int size, String info) {
        this.size = size;
        this.info = info;
    }

    /**
     * @return {@link StandardSize#size}
     */
    public int getSize() {
        return size;
    }

    /**
     * @param size {@link StandardSize#size}
     */
    public void setSize(int size) {
        this.size = size;
    }

    /**
     * @return {@link StandardSize#info}
     */
    public String getInfo() {
        return info;
    }

    /**
     * @param info {@link StandardSize#info}
     */
    public void setInfo(String info) {
        this.info = info;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        StandardSize that = (StandardSize) o;

        if (size != that.size) return false;
        return info != null ? info.equals(that.info) : that.info == null;
    }

    @Override
    public int hashCode() {
        int result = size;
        result = 31 * result + (info != null ? info.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder(getClass().getName());
        sb.append("{size=").append(size);
        sb.append(", info='").append(info).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
