package by.epam.signsControl.webView.tags;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.servlet.jsp.JspException;
import javax.servlet.jsp.tagext.TagSupport;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * tag
 * <p>
 * return current date
 */
public class GetCurrentDate extends TagSupport {

    /**
     * generated by IDEA
     */
    private static final long serialVersionUID = -8654754364947529830L;

    /**
     * logger
     */
    private static final Logger logger = LogManager.getLogger(GetCurrentDate.class);

    /**
     * @return return current date by output stream using server where app located time settings
     * @throws JspException when catch {@link IOException} from {@link javax.servlet.jsp.JspWriter#write(String)}
     */
    @Override
    public int doStartTag() throws JspException {

        logger.info("inside tag start");
        try {
            pageContext.getOut().write(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        } catch (IOException e) {
            logger.warn(e);
            throw new JspException(e.getMessage());
        }

        return SKIP_BODY;
    }
}
