package by.epam.rolesOrganisationsUsersController.bean;

import java.io.Serializable;

/**
 * bean for jdbc field
 *
 * @author Bulgak Alexander
 *
 * @see FactoryType
 * @see Serializable
 */
public class Organisation implements FactoryType, Serializable {

    /**
     * generated by Intellij IDEA
     */
    private static final long serialVersionUID = 2050812806625683000L;

    /**
     * organisation id from jdbc
     */
    private int id;

    /**
     * organisation name from jdbc
     */
    private String name;

    /**
     * members of organisation role id from jdbc
     */
    private int roleID;

    /**
     * members of organisation role from jdbc
     */
    private String role;

    /**
     * block parameter from jdbc
     */
    private boolean isBlocked;

    /**
     * nfo field from jdbc
     */
    private String info;

    /**
     * empty constructor
     */
    public Organisation() {
    }

    /**
     * constructor with all parameters
     *
     * @param id        {@link Organisation#id}
     * @param name      {@link Organisation#name}
     * @param roleID    {@link Organisation#roleID}
     * @param role      {@link Organisation#role}
     * @param isBlocked {@link Organisation#isBlocked}
     * @param info      {@link Organisation#info}
     */
    public Organisation(int id, String name, int roleID, String role, boolean isBlocked, String info) {
        this.id = id;
        this.name = name;
        this.roleID = roleID;
        this.role = role;
        this.isBlocked = isBlocked;
        this.info = info;
    }


    /**
     * @return {@link Organisation#id}
     */
    public int getId() {
        return id;
    }

    /**
     * @param id {@link Organisation#id}
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return {@link Organisation#name}
     */
    public String getName() {
        return name;
    }

    /**
     * @param name {@link Organisation#name}
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return {@link Organisation#roleID}
     */
    public int getRoleID() {
        return roleID;
    }

    /**
     * @param roleID {@link Organisation#roleID}
     */
    public void setRoleID(int roleID) {
        this.roleID = roleID;
    }

    /**
     * @return {@link Organisation#role}
     */
    public String getRole() {
        return role;
    }

    /**
     * @param role {@link Organisation#role}
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * @return {@link Organisation#isBlocked}
     */
    public boolean isBlocked() {
        return isBlocked;
    }

    /**
     * @param blocked {@link Organisation#isBlocked}
     */
    public void setBlocked(boolean blocked) {
        isBlocked = blocked;
    }

    /**
     * @return {@link Organisation#info}
     */
    public String getInfo() {
        return info;
    }

    /**
     * @param info {@link Organisation#info}
     */
    public void setInfo(String info) {
        this.info = info;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Organisation that = (Organisation) o;

        if (id != that.id) return false;
        if (roleID != that.roleID) return false;
        if (isBlocked != that.isBlocked) return false;
        if (name != null ? !name.equals(that.name) : that.name != null) return false;
        if (role != null ? !role.equals(that.role) : that.role != null) return false;
        return info != null ? info.equals(that.info) : that.info == null;
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + roleID;
        result = 31 * result + (role != null ? role.hashCode() : 0);
        result = 31 * result + (isBlocked ? 1 : 0);
        result = 31 * result + (info != null ? info.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Organisation{");
        sb.append("id=").append(id);
        sb.append(", name='").append(name).append('\'');
        sb.append(", roleID=").append(roleID);
        sb.append(", role='").append(role).append('\'');
        sb.append(", isBlocked=").append(isBlocked);
        sb.append(", info='").append(info).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
