package by.epam.rolesOrganisationsUsersController.bean;

import java.io.Serializable;

/**
 * bean for jdbc field
 *
 * @author Bulgak Alexander
 * @see FactoryType
 * @see Serializable
 */
public class Role implements FactoryType, Serializable {

    /**
     * generated by Intellij IDEA
     */
    private static final long serialVersionUID = 3667889031461982406L;

    /**
     * role id from jdbc
     */
    private int id;

    /**
     * role name from jdbc
     */
    private String role;

    /**
     * empty constructor
     */
    public Role() {
    }

    /**
     * constructor with all parameters
     *
     * @param id   {@link Role#id}
     * @param role {@link Role#role}
     */
    public Role(int id, String role) {
        this.id = id;
        this.role = role;
    }

    /**
     * @return {@link Role#id}
     */
    public int getId() {
        return id;
    }

    /**
     * @param id {@link Role#id}
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return {@link Role#role}
     */
    public String getRole() {
        return role;
    }

    /**
     * @param role {@link Role#role}
     */
    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Role role1 = (Role) o;

        if (id != role1.id) return false;
        return role != null ? role.equals(role1.role) : role1.role == null;
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (role != null ? role.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Role{");
        sb.append("id=").append(id);
        sb.append(", role='").append(role).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
