package by.epam.rolesOrganisationsUsersController.bean;

import java.io.Serializable;

/**
 * bean for jdbc field
 *
 * @author Bulgak Alexander
 * @see FactoryType
 * @see Serializable
 */
public class User implements FactoryType, Serializable {

    /**
     * generated by Intellij IDEA
     */
    private static final long serialVersionUID = 6974354527403773473L;

    /**
     * user id from jdbc
     */
    private int id;

    /**
     * user login from jdbc
     */
    private String login;

    /**
     * user role from jdbc
     */
    private int role;

    /**
     * user organisation id from jdbc
     */
    private int organisationID;

    /**
     * user organisation name from jdbc
     */
    private String organisation;

    /**
     * user block from jdbc
     */
    private boolean block;

    /**
     * user name from jdbc
     */
    private String name;

    /**
     * user surname from jdbc
     */
    private String surname;

    /**
     * user info from jdbc
     */
    private String info;

    /**
     * empty constructor
     */
    public User() {
    }

    /**
     * constructor with all parameters
     *
     * @param id             {@link User#id}
     * @param login          {@link User#login}
     * @param role           {@link User#role}
     * @param organisationID {@link User#organisationID}
     * @param organisation   {@link User#organisation}
     * @param block          {@link User#block}
     * @param name           {@link User#name}
     * @param surname        {@link User#surname}
     * @param info           {@link User#info}
     */
    public User(int id, String login, int role, int organisationID, String organisation, boolean block, String name, String surname, String info) {
        this.id = id;
        this.login = login;
        this.role = role;
        this.organisationID = organisationID;
        this.organisation = organisation;
        this.block = block;
        this.name = name;
        this.surname = surname;
        this.info = info;
    }

    /**
     * @return {@link User#role}
     */
    public int getRole() {
        return role;
    }

    /**
     * @param role {@link User#role}
     */
    public void setRole(int role) {
        this.role = role;
    }

    /**
     * @return {@link User#id}
     */
    public int getId() {
        return id;
    }

    /**
     * @param id {@link User#id}
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return {@link User#login}
     */
    public String getLogin() {
        return login;
    }

    /**
     * @param login {@link User#login}
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * @return {@link User#organisationID}
     */
    public int getOrganisationID() {
        return organisationID;
    }

    /**
     * @param organisationID {@link User#organisationID}
     */
    public void setOrganisationID(int organisationID) {
        this.organisationID = organisationID;
    }

    /**
     * @return {@link User#organisation}
     */
    public String getOrganisation() {
        return organisation;
    }

    /**
     * @param organisation {@link User#organisation}
     */
    public void setOrganisation(String organisation) {
        this.organisation = organisation;
    }

    /**
     * @return {@link User#block}
     */
    public boolean isBlock() {
        return block;
    }

    /**
     * @param block {@link User#block}
     */
    public void setBlock(boolean block) {
        this.block = block;
    }

    /**
     * @return {@link User#name}
     */
    public String getName() {
        return name;
    }

    /**
     * @param name {@link User#name}
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return {@link User#surname}
     */
    public String getSurname() {
        return surname;
    }

    /**
     * @param surname {@link User#surname}
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * @return {@link User#info}
     */
    public String getInfo() {
        return info;
    }

    /**
     * @param info {@link User#info}
     */
    public void setInfo(String info) {
        this.info = info;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("User{");
        sb.append("id=").append(id);

        if (login != null) {
            sb.append(", login='").append(login).append('\'');
        }

        sb.append(", role=").append(role);
        sb.append(", organisationID=").append(organisationID);
        sb.append(", organisation='").append(organisation).append('\'');
        sb.append(", block=").append(block);
        sb.append(", name='").append(name).append('\'');
        sb.append(", surname='").append(surname).append('\'');
        sb.append(", info='").append(info).append('\'');
        sb.append('}');
        return sb.toString();
    }

}
