package by.epam.rolesOrganisationsUsersController.bean;

import java.io.Serializable;

/**
 * bean for jdbc field
 *
 * @author Bulgak Alexander
 * @see FactoryType
 * @see Serializable
 */
public class User implements FactoryType, Serializable{

    /**
     * generated by Intellij IDEA
     */
    private static final long serialVersionUID = 6974354527403773473L;

    /**
     * user id from jdbc
     */
    private int id;

    /**
     * user login from jdbc
     */
    private String login;

    /**
     * user role {@link Role}
     */
    private Role role;

    /**
     * user organisation {@link Organisation}
     */
    private Organisation organisation;

    /**
     * user block from jdbc
     */
    private boolean block;

    /**
     * user name from jdbc
     */
    private String name;

    /**
     * user surname from jdbc
     */
    private String surname;

    /**
     * user info from jdbc
     */
    private String info;

    /**
     * empty constructor
     */
    public User() {
    }

    /**
     * constructor with all parameters
     *
     * @param id           {@link User#id}
     * @param login        {@link User#login}
     * @param role         {@link User#role}
     * @param organisation {@link User#organisation}
     * @param block        {@link User#block}
     * @param name         {@link User#name}
     * @param surname      {@link User#surname}
     * @param info         {@link User#info}
     */
    public User(int id, String login, Role role, Organisation organisation, boolean block, String name, String surname, String info) {
        this.id = id;
        this.login = login;
        this.role = role;
        this.organisation = organisation;
        this.block = block;
        this.name = name;
        this.surname = surname;
        this.info = info;
    }

    /**
     * @return {@link User#role}
     */
    public Role getRole() {
        return (Role)role.clone();
    }

    /**
     * @param role {@link User#role}
     */
    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * @return {@link User#id}
     */
    public int getId() {
        return id;
    }

    /**
     * @param id {@link User#id}
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return {@link User#login}
     */
    public String getLogin() {
        return login;
    }

    /**
     * @param login {@link User#login}
     */
    public void setLogin(String login) {
        this.login = login;
    }



    /**
     * @return {@link User#organisation}
     */
    public Organisation getOrganisation() {
        return (Organisation)organisation.clone();
    }

    /**
     * @param organisation {@link User#organisation}
     */
    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }

    /**
     * @return {@link User#block}
     */
    public boolean isBlock() {
        return block;
    }

    /**
     * @param block {@link User#block}
     */
    public void setBlock(boolean block) {
        this.block = block;
    }

    /**
     * @return {@link User#name}
     */
    public String getName() {
        return name;
    }

    /**
     * @param name {@link User#name}
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return {@link User#surname}
     */
    public String getSurname() {
        return surname;
    }

    /**
     * @param surname {@link User#surname}
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * @return {@link User#info}
     */
    public String getInfo() {
        return info;
    }

    /**
     * @param info {@link User#info}
     */
    public void setInfo(String info) {
        this.info = info;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        User user = (User) o;

        if (id != user.id) return false;
        if (block != user.block) return false;
        if (login != null ? !login.equals(user.login) : user.login != null) return false;
        if (role != null ? !role.equals(user.role) : user.role != null) return false;
        if (organisation != null ? !organisation.equals(user.organisation) : user.organisation != null) return false;
        if (name != null ? !name.equals(user.name) : user.name != null) return false;
        if (surname != null ? !surname.equals(user.surname) : user.surname != null) return false;
        return info != null ? info.equals(user.info) : user.info == null;
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (login != null ? login.hashCode() : 0);
        result = 31 * result + (role != null ? role.hashCode() : 0);
        result = 31 * result + (organisation != null ? organisation.hashCode() : 0);
        result = 31 * result + (block ? 1 : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (surname != null ? surname.hashCode() : 0);
        result = 31 * result + (info != null ? info.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("User{");
        sb.append("id=").append(id);
        sb.append(", login='").append(login).append('\'');
        sb.append(", role=").append(role);
        sb.append(", organisation=").append(organisation);
        sb.append(", block=").append(block);
        sb.append(", name='").append(name).append('\'');
        sb.append(", surname='").append(surname).append('\'');
        sb.append(", info='").append(info).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
