package by.epam.orders.bean;

import by.epam.rolesOrganisationsUsersController.bean.Organisation;
import by.epam.signsControl.bean.Sign;

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * class for sql field
 */
public class Order implements Serializable, FactoryType, Cloneable {

    /**
     * generated by IDEA
     */
    private static final long serialVersionUID = -2927331317579971691L;

    /**
     * order id
     */
    private int id;

    /**
     * sign list id
     */
    private int signList;

    /**
     * {@link Sign} in order
     */
    private Sign sign;

    /**
     * standard size id
     */
    private int standardSize;

    /**
     * {@link Organisation} customer organisation
     */
    private Organisation customerOrganisation;

    /**
     * transaction id from order
     */
    private int transactionID;

    /**
     * transaction money from order
     */
    private double transactionMoney;

    /**
     * order's type of work {@link TypeOfWork}
     */
    private TypeOfWork typeOfWork;

    /**
     * workers crew id
     */
    private int workersCrew;

    /**
     * date of add order
     */
    private Timestamp dateOfOrder;

    /**
     * date of execute order
     */
    private Timestamp dateOfExecution;

    /**
     * order info
     */
    private String info;

    /**
     * empty constructor
     */
    public Order() {
    }


    /**
     * constructor with all parameters
     *
     * @param id                   {@link Order#id}
     * @param signList             {@link Order#signList}
     * @param sign                 {@link Order#sign}
     * @param standardSize         {@link Order#standardSize}
     * @param customerOrganisation {@link Order#customerOrganisation}
     * @param transactionID        {@link Order#transactionID}
     * @param transactionMoney     {@link Order#transactionMoney}
     * @param typeOfWork           {@link Order#typeOfWork}
     * @param workersCrew          {@link Order#workersCrew}
     * @param dateOfOrder          {@link Order#dateOfOrder}
     * @param dateOfExecution      {@link Order#dateOfExecution}
     * @param info                 {@link Order#info}
     */
    public Order(int id, int signList, Sign sign, int standardSize, Organisation customerOrganisation,
                 int transactionID, double transactionMoney, TypeOfWork typeOfWork, int workersCrew, Timestamp dateOfOrder,
                 Timestamp dateOfExecution, String info) {
        this.id = id;
        this.signList = signList;
        this.sign = sign;
        this.standardSize = standardSize;
        this.customerOrganisation = customerOrganisation;
        this.transactionID = transactionID;
        this.transactionMoney = transactionMoney;
        this.typeOfWork = typeOfWork;
        this.workersCrew = workersCrew;
        this.dateOfOrder = dateOfOrder;
        this.dateOfExecution = dateOfExecution;
        this.info = info;
    }

    /**
     * @return this object clone
     */
    @Override
    protected Object clone() {
        try {
            Order order = (Order) super.clone();
            order.sign = this.getSign();
            order.customerOrganisation = this.getCustomerOrganisation();
            order.typeOfWork = this.getTypeOfWork();
            return order;
        } catch (CloneNotSupportedException e) {
            // this shouldn't happen, since we are Cloneable
            throw new InternalError(e);
        }
    }

    /**
     * @return {@link Order#id}
     */
    public int getId() {
        return id;
    }

    /**
     * @param id {@link Order#id}
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return {@link Order#sign}
     */
    public Sign getSign() {
        return sign;
    }

    /**
     * @param sign {@link Order#sign}
     */
    public void setSign(Sign sign) {
        this.sign = (Sign) sign.clone();
    }

    /**
     * @return {@link Order#standardSize}
     */
    public int getStandardSize() {
        return standardSize;
    }

    /**
     * @param standardSize {@link Order#standardSize}
     */
    public void setStandardSize(int standardSize) {
        this.standardSize = standardSize;
    }

    /**
     * @return {@link Order#customerOrganisation}
     */
    public Organisation getCustomerOrganisation() {
        return (Organisation) customerOrganisation.clone();
    }

    /**
     * @param customerOrganisation {@link Order#customerOrganisation}
     */
    public void setCustomerOrganisation(Organisation customerOrganisation) {
        this.customerOrganisation = customerOrganisation;
    }

    /**
     * @return {@link Order#signList}
     */
    public int getSignList() {
        return signList;
    }

    /**
     * @param signList {@link Order#signList}
     */
    public void setSignList(int signList) {
        this.signList = signList;
    }

    /**
     * @return {@link Order#transactionID}
     */
    public int getTransactionID() {
        return transactionID;
    }

    /**
     * @param transactionID {@link Order#transactionID}
     */
    public void setTransactionID(int transactionID) {
        this.transactionID = transactionID;
    }

    /**
     * @return {@link Order#transactionMoney}
     */
    public double getTransactionMoney() {
        return transactionMoney;
    }

    /**
     * @param transactionMoney {@link Order#transactionMoney}
     */
    public void setTransactionMoney(double transactionMoney) {
        this.transactionMoney = transactionMoney;
    }

    /**
     * @return {@link Order#typeOfWork}
     */
    public TypeOfWork getTypeOfWork() {

        return (TypeOfWork) typeOfWork.clone();

    }

    /**
     * @param typeOfWork {@link Order#typeOfWork}
     */
    public void setTypeOfWork(TypeOfWork typeOfWork) {
        this.typeOfWork = typeOfWork;
    }

    /**
     * @return {@link Order#workersCrew}
     */
    public int getWorkersCrew() {
        return workersCrew;
    }

    /**
     * @param workersCrew {@link Order#workersCrew}
     */
    public void setWorkersCrew(int workersCrew) {
        this.workersCrew = workersCrew;
    }

    /**
     * @return {@link Order#dateOfOrder}
     */
    public Timestamp getDateOfOrder() {
        return dateOfOrder;
    }

    /**
     * @param dateOfOrder {@link Order#dateOfOrder}
     */
    public void setDateOfOrder(Timestamp dateOfOrder) {
        this.dateOfOrder = dateOfOrder;
    }

    /**
     * @return {@link Order#dateOfExecution}
     */
    public Timestamp getDateOfExecution() {
        return dateOfExecution;
    }

    /**
     * @param dateOfExecution {@link Order#dateOfExecution}
     */
    public void setDateOfExecution(Timestamp dateOfExecution) {
        this.dateOfExecution = dateOfExecution;
    }

    /**
     * @return {@link Order#info}
     */
    public String getInfo() {
        return info;
    }

    /**
     * @param info {@link Order#info}
     */
    public void setInfo(String info) {
        this.info = info;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Order order = (Order) o;

        if (id != order.id) return false;
        if (signList != order.signList) return false;
        if (standardSize != order.standardSize) return false;
        if (transactionID != order.transactionID) return false;
        if (Double.compare(order.transactionMoney, transactionMoney) != 0) return false;
        if (workersCrew != order.workersCrew) return false;
        if (sign != null ? !sign.equals(order.sign) : order.sign != null) return false;
        if (customerOrganisation != null ? !customerOrganisation.equals(order.customerOrganisation) : order.customerOrganisation != null)
            return false;
        if (typeOfWork != null ? !typeOfWork.equals(order.typeOfWork) : order.typeOfWork != null) return false;
        if (dateOfOrder != null ? !dateOfOrder.equals(order.dateOfOrder) : order.dateOfOrder != null) return false;
        if (dateOfExecution != null ? !dateOfExecution.equals(order.dateOfExecution) : order.dateOfExecution != null)
            return false;
        return info != null ? info.equals(order.info) : order.info == null;
    }

    @Override
    public int hashCode() {
        int result;
        long temp;
        result = id;
        result = 31 * result + signList;
        result = 31 * result + (sign != null ? sign.hashCode() : 0);
        result = 31 * result + standardSize;
        result = 31 * result + (customerOrganisation != null ? customerOrganisation.hashCode() : 0);
        result = 31 * result + transactionID;
        temp = Double.doubleToLongBits(transactionMoney);
        result = 31 * result + (int) (temp ^ (temp >>> 32));
        result = 31 * result + (typeOfWork != null ? typeOfWork.hashCode() : 0);
        result = 31 * result + workersCrew;
        result = 31 * result + (dateOfOrder != null ? dateOfOrder.hashCode() : 0);
        result = 31 * result + (dateOfExecution != null ? dateOfExecution.hashCode() : 0);
        result = 31 * result + (info != null ? info.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Order{");
        sb.append("id=").append(id);
        sb.append(", signList=").append(signList);
        sb.append(", sign=").append(sign);
        sb.append(", standardSize=").append(standardSize);
        sb.append(", customerOrganisation=").append(customerOrganisation);
        sb.append(", transactionID=").append(transactionID);
        sb.append(", transactionMoney=").append(transactionMoney);
        sb.append(", typeOfWork=").append(typeOfWork);
        sb.append(", workersCrew=").append(workersCrew);
        sb.append(", dateOfOrder=").append(dateOfOrder);
        sb.append(", dateOfExecution=").append(dateOfExecution);
        sb.append(", info='").append(info).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
