package by.epam.orders.bean;

import by.epam.rolesOrganisationsUsersController.bean.Organisation;
import by.epam.rolesOrganisationsUsersController.bean.User;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;

/**
 * class for sql workers crews
 */
public class WorkersCrew implements Serializable, FactoryType {

    /**
     * generated by idea
     */
    private static final long serialVersionUID = -5085596337299968847L;

    /**
     * id of workers crew
     */
    private int id;

    /**
     * list of workers- {@link User}
     */
    private ArrayList<User> workers = new ArrayList<>();

    /**
     * date of create
     */
    private Date creationDate;

    /**
     * date of remove
     */
    private Date removeDate;

    /**
     * information
     */
    private String info;

    /**
     * {@link Organisation}
     */
    private Organisation organisation;

    /**
     * empty constructor
     */
    public WorkersCrew() {
    }

    /**
     * constructor with all parameters
     *
     * @param id           {@link WorkersCrew#id}
     * @param workers      {@link WorkersCrew#workers}
     * @param creationDate {@link WorkersCrew#creationDate}
     * @param removeDate   {@link WorkersCrew#removeDate}
     * @param info         {@link WorkersCrew#info}
     * @param organisation {@link WorkersCrew#organisation}
     */
    public WorkersCrew(int id, ArrayList<User> workers, Date creationDate, Date removeDate, String info, Organisation organisation) {
        this.id = id;
        this.workers = workers;
        this.creationDate = creationDate;
        this.removeDate = removeDate;
        this.info = info;
        this.organisation = organisation;
    }

    /**
     * constructor
     *
     * @param id      {@link WorkersCrew#id}
     * @param workers {@link WorkersCrew#workers}
     */
    public WorkersCrew(int id, ArrayList<User> workers) {
        this.id = id;
        this.workers = workers;
    }

    /**
     * @return {@link WorkersCrew#organisation} clone
     */
    public Organisation getOrganisation() {
        return organisation == null ? null : (Organisation) organisation.clone();
    }

    /**
     * @param organisation {@link WorkersCrew#organisation}
     */
    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }


    /**
     * {@link WorkersCrew#workers} empty arr
     */
    public void setNewWorkersArr() {
        workers = new ArrayList<>();
    }

    /**
     * @param worker {@link User} to add in {@link WorkersCrew#workers}
     */
    public void addWorker(User worker) {
        workers.add(worker);
    }

    /**
     * get worker from  {@link WorkersCrew#workers}
     *
     * @param position positin to get
     * @return {@link User} worker on this position
     */
    public User getWorker(int position) {
        return workers.get(position);
    }

    /**
     * @return {@link WorkersCrew#id}
     */
    public int getId() {
        return id;
    }

    /**
     * @param id {@link WorkersCrew#id}
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return {@link WorkersCrew#workers} clone
     */
    public ArrayList<User> getWorkers() {
        return workers == null ? null : (ArrayList<User>) workers.clone();
    }

    /**
     * @param workers {@link WorkersCrew#workers}
     */
    public void setWorkers(ArrayList<User> workers) {
        this.workers = workers;
    }

    /**
     * @return {@link WorkersCrew#creationDate} clone
     */
    public Date getCreationDate() {
        return creationDate == null ? null : (Date) creationDate.clone();
    }

    /**
     * @param creationDate {@link WorkersCrew#creationDate}
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * @return {@link WorkersCrew#removeDate} clone
     */
    public Date getRemoveDate() {
        return removeDate == null ? null : (Date) removeDate.clone();
    }

    /**
     * @param removeDate {@link WorkersCrew#removeDate}
     */

    public void setRemoveDate(Date removeDate) {
        this.removeDate = removeDate;
    }

    /**
     * @return {@link WorkersCrew#info}
     */
    public String getInfo() {
        return info;
    }

    /**
     * @param info {@link WorkersCrew#info}
     */
    public void setInfo(String info) {
        this.info = info;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        WorkersCrew that = (WorkersCrew) o;

        if (id != that.id) return false;
        if (workers != null ? !workers.equals(that.workers) : that.workers != null) return false;
        if (creationDate != null ? !creationDate.equals(that.creationDate) : that.creationDate != null) return false;
        if (removeDate != null ? !removeDate.equals(that.removeDate) : that.removeDate != null) return false;
        if (info != null ? !info.equals(that.info) : that.info != null) return false;
        return organisation != null ? organisation.equals(that.organisation) : that.organisation == null;
    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + (workers != null ? workers.hashCode() : 0);
        result = 31 * result + (creationDate != null ? creationDate.hashCode() : 0);
        result = 31 * result + (removeDate != null ? removeDate.hashCode() : 0);
        result = 31 * result + (info != null ? info.hashCode() : 0);
        result = 31 * result + (organisation != null ? organisation.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("WorkersCrew{");
        sb.append("id=").append(id);
        sb.append(", workers=").append(workers);
        sb.append(", creationDate=").append(creationDate);
        sb.append(", removeDate=").append(removeDate);
        sb.append(", info='").append(info).append('\'');
        sb.append(", organisation=").append(organisation);
        sb.append('}');
        return sb.toString();
    }
}
